### ISSUE TITLE
Package request: Floorp

### ISSUE THREAD

**Issue by lunik1** [bandithedoge/nixpkgs-firefox-darwin#10]
Would it be possible to add [floorp](https://floorp.app/en/) to this overlay? It is a Firefox fork with some extra features. MacOS binaries are available.

The nixpkgs recipe is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/wrapper.nix).

**Comment by kbwhodat** [comment]
@bandithedoge I created a PR for adding Floorp: https://github.com/bandithedoge/nixpkgs-firefox-darwin/pull/11
I've been using it for a while now. I was not able to use undmg as I would get this error: `only HFS file systems are supported.`. It appears that Floorp does not provide HFS DMGs. Hence why I ended using `_7zz`.

For anyone wanting Floorp to work on both nix-darwin and nixos with your userChrome.css, user.js, extensions etc applied this is a module a referenced from an individual:

https://github.com/kbwhodat/configs/blob/main/nix-config/modules/floorp.nix

From there you can reference the module:

https://github.com/kbwhodat/configs/blob/main/nix-config/common/browsers/floorp.nix
