### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by atahanyorganci** [bandithedoge/nixpkgs-firefox-darwin#15]
I have forked the repository and I made some changes to support adding `policies.json` through home-managre.  I want to add MIT license to my fork of the project. Since, this project doesn't have a license, I'm delaying it. If you can add a license, I can choose a license for mine as well.

**Comment by bandithedoge** [comment]
Well, this is awkward. I forgot to add a license and haven't noticed for 3 years. Unfortunately I can't just add a LICENSE file and call it a day without written permission from every contributor.

~~@harukafractus~~ ~~@themg95~~ ~~@lunik1~~ ~~@katoby~~ ~~@jordan-bravo~~

Do you agree to have this repository (including your contributions) licensed under the MIT license?

**Comment by lunik1** [comment]
Mine is only a tiny doc change but sure :)

I also agree to any other OSI or FSF approved licence fwiw.

**Comment by themg95** [comment]
I agree

**Comment by jordan-bravo** [comment]
I agree

**Comment by kbwhodat** [comment]
@katoby is my other Git user. And yes I agree

**Comment by fractuscontext** [comment]
I agree
