### ISSUE TITLE
Package Request: LibreWolf

### ISSUE THREAD

**Issue by Guanran928** [bandithedoge/nixpkgs-firefox-darwin#3]
Hi,

I have been using LibreWolf with Homebrew for a while.

It would be really nice if you also package LibreWolf, which is a fork of Firefox and focused on privacy.

Thank you for your work :P

**Comment by Guanran928** [comment]
I believe binaries are available here: https://gitlab.com/librewolf-community/browser/bsys6/-/releases

**Comment by fractuscontext** [comment]
Maybe you could take a look at my overlay here. I haven’t created a pull request yet because I’m still working on resolving some branch conflicts.

https://github.com/harukafractus/nixpkgs-firefox-darwin

**Comment by bandithedoge** [comment]
> Maybe you could take a look at my overlay here. I haven’t created a pull request yet because I’m still working on resolving some branch conflicts.
> 
> [harukafractus/nixpkgs-librewolf-firefox-darwin](https://github.com/harukafractus/nixpkgs-librewolf-firefox-darwin)

I just merged #8 so you should try again now. Since I don't have access to a Mac anymore it'd be great if you could create a PR.

**Comment by fractuscontext** [comment]
I’ve created a new pull request to address the issue. Perhaps granting me read/write access to the repository would facilitate faster changes and better maintenance in case of any future updates?
