### ISSUE TITLE
Inquiry about how to consume the overlay

### ISSUE THREAD

**Issue by createchange** [bandithedoge/nixpkgs-firefox-darwin#6]
Hi there, I am a bit (ok, that's an understatement) of a nix noob, and I am looking for help on how to actually use the overlay. When I use the minimal configuration provided in the README, and then try to install firefox, it is still referencing the wrong package. I am clearly doing something wrong, and it is not referencing the overlay.

flake.nix
```
{
  description = "Darwin system flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:LnL7/nix-darwin";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixpkgs-firefox-darwin.url = "github:bandithedoge/nixpkgs-firefox-darwin";
  };

  outputs = inputs @ {
    self,
    nixpkgs,
    nix-darwin,
    home-manager,
    nixpkgs-firefox-darwin,
    ...
  }: let
    username = "redacted";
    useremail = "redacted";
    system = "aarch64-darwin";
    hostname = "redacted";
    specialArgs =
      inputs
      // {
        inherit username useremail hostname;
      };
  in {
    # Build darwin flake using:
    # $ darwin-rebuild build --flake .#{hostname}
    darwinConfigurations."${hostname}" = nix-darwin.lib.darwinSystem {
      inherit system specialArgs;
      modules = [
	./modules/nix-core.nix
	./modules/host-users.nix
	./modules/system.nix
        ./modules/homebrew.nix
        home-manager.darwinModules.home-manager
        {
          nixpkgs.overlays = [ inputs.nixpkgs-firefox-darwin.overlay ]; 
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.extraSpecialArgs = specialArgs;
          home-manager.users.${username} = import ./home;
        }
      ];
    };
  };
}

```

home/default.nix
```
{username, pkgs, ...}: {
  imports = [
    ./core.nix
    ./git.nix
    ./zsh.nix
    ./starship.nix
    ./tmux.nix
    ./neovim
    ./firefox.nix
  ];

  home = {
    username = username;
    stateVersion = "23.11";
  };

  programs.home-manager.enable = true;
}

```

home/firefox.nix
```
{ pkgs, ... }: {
  programs.firefox = {
    enable = true;
  };
}
```

And the error to demonstrate that it must be referencing the native package:
```
         package.meta.badPlatforms = [
           "x86_64-darwin"
           "i686-darwin"
           "aarch64-darwin"
           "armv7a-darwin"
         ]
       , refusing to evaluate.
```

Any insight you can provide would be immensely helpful. Looking to automate onboarding team members, and being able to do things like pre-install firefox extensions would be much better than the basic homebrew install I am currently doing.

**Comment by mjm** [comment]
In `home/firefox.nix`, I think you just need to set `package = pkgs.firefox-bin;` inside `programs.firefox`. That's the package this overlay exposes, but the default is `pkgs.firefox`;

**Comment by bandithedoge** [comment]
Exactly as @mjm said, the overlay provides `firefox-bin` instead of overriding the default `firefox`. I should've added this to the README.

**Comment by createchange** [comment]
That absolutely did solve the problem - thanks! Unfortunately, I had to revert to using Homebrew for Firefox, due to other tools that I use (namely, [granted.dev](https://www.granted.dev/)) not playing nicely with a nix-managed Firefox install.

Nonetheless, I appreciate the quick responses!
